/*
 * The ROM images compiled into the binary, generated by
 * tools/jzintv/embed-roms.py.
 *
 * jzIntv resolves EXEC/GROM by exact path (the -e/-g flags), so
 * intv_host.c materialises this table into the session's ROM directory on
 * first start and passes -e/-g pointing at it. An entry is skipped when a
 * file of that name is already there, so a ROM the user imported always
 * wins over the compiled-in one.
 *
 * One class only: EXEC and GROM are both Mattel copyrighted firmware, unlike
 * the CoCo port's split between a freely-redistributable and a system class.
 * This table is non-empty only in a WITH_INTV_ROMS=ON build, which must not
 * be redistributed -- every artifact this repository publishes is built
 * WITH_INTV_ROMS=OFF, and core/tests/no_embedded_roms.py checks that claim
 * against the shipped binaries. See COMPLIANCE.md.
 *
 * Copyright (C) 2026 Thomas Cherryhomes
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

#ifndef INTV_ROMS_EMBEDDED_H
#define INTV_ROMS_EMBEDDED_H

#include <stddef.h>

typedef struct {
    const char *name;            /* exact filename, e.g. "exec.bin" */
    const unsigned char *data;
    size_t size;                 /* generated from sizeof, so size_t exactly */
} intv_embedded_rom;

extern const intv_embedded_rom intv_embedded_roms[];
extern const int intv_embedded_rom_count;

#endif /* INTV_ROMS_EMBEDDED_H */
